spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create #none #validate
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # 웬만하면 옵션을 설정하는 것이 좋음 (디테일하게 설정하고 싶으면 @BatchSize로 적용)
  h2:
    console:
      enabled: true


logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace #스프링 부트 2.x, hibernate5
  # org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
